<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTypesSeeder extends Seeder
{
    public function run()
    {
        if (DB::table('product_types')->count() == 0) {
            DB::table('product_types')->insert([
                ['id' => 1, 'description' => 'Cheese'],
                ['id' => 2, 'description' => 'Turkey Ham'],
                ['id' => 3, 'description' => 'Lettuce'],
                ['id' => 4, 'description' => 'Wheat Flour'],
                ['id' => 5, 'description' => 'Condensed Milk'],
                ['id' => 6, 'description' => 'Sliced Bread'],
                ['id' => 7, 'description' => 'Whole Wheat Bread'],
                ['id' => 8, 'description' => 'Baguette'],
                ['id' => 9, 'description' => 'Hard Boiled Eggs'],
                ['id' => 10, 'description' => 'Yogurt'],
                ['id' => 11, 'description' => 'Skim Milk'],
                ['id' => 12, 'description' => 'Whole Milk'],
                ['id' => 13, 'description' => 'Kefir'],
                ['id' => 14, 'description' => 'Blueberries'],
                ['id' => 15, 'description' => 'Bananas'],
                ['id' => 16, 'description' => 'Apples'],
                ['id' => 17, 'description' => 'Strawberries'],
                ['id' => 18, 'description' => 'Carrots'],
                ['id' => 19, 'description' => 'Potatoes'],
                ['id' => 20, 'description' => 'Tomatoes'],
                ['id' => 21, 'description' => 'Olive Oil'],
                ['id' => 22, 'description' => 'Canola Oil'],
                ['id' => 23, 'description' => 'Sunflower Oil'],
                ['id' => 24, 'description' => 'Margarine'],
                ['id' => 25, 'description' => 'Butter'],
                ['id' => 26, 'description' => 'Biscuits'],
                ['id' => 27, 'description' => 'Cookies'],
                ['id' => 28, 'description' => 'Crackers'],
                ['id' => 29, 'description' => 'Beef Steak'],
                ['id' => 30, 'description' => 'Ground Beef'],
                ['id' => 31, 'description' => 'Chicken Breast'],
                ['id' => 32, 'description' => 'Sliced Turkey'],
                ['id' => 33, 'description' => 'Salami'],
                ['id' => 34, 'description' => 'Prosciutto'],
                ['id' => 35, 'description' => 'Tofu'],
                ['id' => 36, 'description' => 'Almond Milk'],
                ['id' => 37, 'description' => 'Coconut Milk'],
                ['id' => 38, 'description' => 'Rice Milk'],
                ['id' => 39, 'description' => 'Red Wine'],
                ['id' => 40, 'description' => 'White Wine'],
                ['id' => 41, 'description' => 'Sparkling Water'],
                ['id' => 42, 'description' => 'Juice'],
                ['id' => 43, 'description' => 'Coffee Beans'],
                ['id' => 44, 'description' => 'Tea Leaves'],
                ['id' => 45, 'description' => 'Herbal Teas'],
                ['id' => 46, 'description' => 'Green Tea'],
                ['id' => 47, 'description' => 'Black Tea'],
                ['id' => 48, 'description' => 'Sweet Corn'],
                ['id' => 49, 'description' => 'Green Peas'],
                ['id' => 50, 'description' => 'Chickpeas'],
                ['id' => 51, 'description' => 'Lentils'],
                ['id' => 52, 'description' => 'Black Beans'],
                ['id' => 53, 'description' => 'Spaghetti'],
                ['id' => 54, 'description' => 'Macaroni'],
                ['id' => 55, 'description' => 'Lasagna Noodles'],
                ['id' => 56, 'description' => 'Rice'],
                ['id' => 57, 'description' => 'White Rice'],
                ['id' => 58, 'description' => 'Brown Rice'],
                ['id' => 59, 'description' => 'Basmati Rice'],
                ['id' => 60, 'description' => 'Jasmine Rice'],
                ['id' => 61, 'description' => 'Sushi Rice'],
                ['id' => 62, 'description' => 'Quinoa'],
                ['id' => 63, 'description' => 'Couscous'],
                ['id' => 64, 'description' => 'Polenta'],
                ['id' => 65, 'description' => 'Tomato Sauce'],
                ['id' => 66, 'description' => 'Alfredo Sauce'],
                ['id' => 67, 'description' => 'Pesto Sauce'],
                ['id' => 68, 'description' => 'Mayonnaise'],
                ['id' => 69, 'description' => 'Mustard'],
                ['id' => 70, 'description' => 'Ketchup'],
                ['id' => 71, 'description' => 'Barbecue Sauce'],
                ['id' => 72, 'description' => 'Hot Sauce'],
                ['id' => 73, 'description' => 'Salad Dressing'],
                ['id' => 74, 'description' => 'Honey'],
                ['id' => 75, 'description' => 'Maple Syrup'],
                ['id' => 76, 'description' => 'Jam'],
                ['id' => 77, 'description' => 'Jelly'],
                ['id' => 78, 'description' => 'Peanut Butter'],
                ['id' => 79, 'description' => 'Almond Butter'],
                ['id' => 80, 'description' => 'Walnuts'],
                ['id' => 81, 'description' => 'Almonds'],
                ['id' => 82, 'description' => 'Peanuts'],
                ['id' => 83, 'description' => 'Cashews'],
                ['id' => 84, 'description' => 'Pistachios'],
                ['id' => 85, 'description' => 'Sunflower Seeds'],
                ['id' => 86, 'description' => 'Chia Seeds'],
                ['id' => 87, 'description' => 'Flaxseeds'],
                ['id' => 88, 'description' => 'Sesame Seeds'],
                ['id' => 89, 'description' => 'Pumpkin Seeds'],
                ['id' => 90, 'description' => 'Garlic Bread'],
                ['id' => 91, 'description' => 'Chocolate'],
                ['id' => 92, 'description' => 'Dark Chocolate'],
                ['id' => 93, 'description' => 'Milk Chocolate'],
                ['id' => 94, 'description' => 'White Chocolate'],
                ['id' => 95, 'description' => 'Ice Cream'],
                ['id' => 96, 'description' => 'Sorbet'],
                ['id' => 97, 'description' => 'Gelato'],
                ['id' => 98, 'description' => 'Coconut Water'],
                ['id' => 99, 'description' => 'Mineral Water'],
                ['id' => 100, 'description' => 'Sparkling Wine'],
                ['id' => 101, 'description' => 'Soft Drink'],
                ['id' => 102, 'description' => 'Rosé Wine'],
                ['id' => 103, 'description' => 'Cabernet Sauvignon'],
                ['id' => 104, 'description' => 'Pale Ale'],
                ['id' => 105, 'description' => 'Pilsner Lager'],
            ]);
        }
    }
}
