<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTypesSeeder extends Seeder
{
    public function run()
    {
        if (DB::table('product_types')->count() == 0) {
            DB::table('product_types')->insert([
                ['id' => 1, 'description' => 'Coliflor'],
                ['id' => 2, 'description' => 'Mantequilla'],
                ['id' => 3, 'description' => 'Diente de ajo'],
                ['id' => 4, 'description' => 'Harina'],
                ['id' => 5, 'description' => 'Leche'],
                ['id' => 6, 'description' => 'Queso'],
                ['id' => 7, 'description' => 'Queso Parmesano'],
                ['id' => 8, 'description' => 'Sal'],
                ['id' => 9, 'description' => 'Pimienta'],
                ['id' => 10, 'description' => 'Perejil'],
                ['id' => 11, 'description' => 'Lomo Liso, Asiento o Posta'],
                ['id' => 12, 'description' => 'Cebolla'],
                ['id' => 13, 'description' => 'Papas'],
                ['id' => 14, 'description' => 'Aceite'],
                ['id' => 15, 'description' => 'Huevos'],
                ['id' => 16, 'description' => 'Orégano'],
                ['id' => 17, 'description' => 'Comino'],
                ['id' => 18, 'description' => 'Asiento'],
                ['id' => 19, 'description' => 'Aceite de maravilla'],
                ['id' => 20, 'description' => 'Zanahorias'],
                ['id' => 21, 'description' => 'Hoja de laurel'],
                ['id' => 22, 'description' => 'Rama de romero'],
                ['id' => 23, 'description' => 'Vino tinto'],
                ['id' => 24, 'description' => 'Caldo de carne'],
                ['id' => 25, 'description' => 'Cebolla morada'],
                ['id' => 26, 'description' => 'Arándanos frescos'],
                ['id' => 27, 'description' => 'Ron'],
                ['id' => 28, 'description' => 'Menta'],
                ['id' => 29, 'description' => 'Azúcar'],
                ['id' => 30, 'description' => 'Jugo de limon'],
                ['id' => 31, 'description' => 'Agua con gas o soda'],
                ['id' => 32, 'description' => 'Hielo'],
                ['id' => 33, 'description' => 'Azúcar moreno'],
                ['id' => 34, 'description' => 'Ajo en polvo'],
                ['id' => 35, 'description' => 'Pimienta negra'],
                ['id' => 36, 'description' => 'Cebolla en polvo'],
                ['id' => 37, 'description' => 'Azúcar blanco'],
                ['id' => 38, 'description' => 'Merkén'],
                ['id' => 39, 'description' => 'Jugo de naranja'],
                ['id' => 40, 'description' => 'Miel'],
                ['id' => 41, 'description' => 'Extracto de vainilla'],
                ['id' => 42, 'description' => 'Jengibre en polvo'],
                ['id' => 43, 'description' => 'Manzanas Fuji'],
                ['id' => 44, 'description' => 'Carne'],
                ['id' => 45, 'description' => 'Ají de color'],
                ['id' => 46, 'description' => 'Pasas rubias'],
                ['id' => 47, 'description' => 'Aceitunas negras'],
                ['id' => 48, 'description' => 'Aceite de oliva'],
                ['id' => 49, 'description' => 'Plateada'],
                ['id' => 50, 'description' => 'Pimentón'],
                ['id' => 51, 'description' => 'Pastelera de choclo congelada'],
                ['id' => 52, 'description' => 'Hojas de albahaca'],
                ['id' => 53, 'description' => 'Pesto'],
                ['id' => 54, 'description' => 'Vino blanco'],
                ['id' => 55, 'description' => 'Chuleta Kassler'],
                ['id' => 56, 'description' => 'Repollo morado'],
                ['id' => 57, 'description' => 'Chucrut'],
                ['id' => 58, 'description' => 'Mostaza'],
                ['id' => 59, 'description' => 'Betarraga'],
                ['id' => 60, 'description' => 'Yogurt natural'],
                ['id' => 61, 'description' => 'Caldo vegetal'],
                ['id' => 62, 'description' => 'Espárragos'],
                ['id' => 63, 'description' => 'Pasta'],
                ['id' => 64, 'description' => 'Yogurt griego'],
                ['id' => 65, 'description' => 'Zeste de limón'],
                ['id' => 66, 'description' => 'Eneldo'],
                ['id' => 67, 'description' => 'Frutillas'],
                ['id' => 68, 'description' => 'Plátano'],
                ['id' => 69, 'description' => 'Leche con chocolate'],
                ['id' => 70, 'description' => 'Cacao'],
                ['id' => 71, 'description' => 'Coco'],
                ['id' => 72, 'description' => 'Semillas'],
                ['id' => 73, 'description' => 'Chocochips'],
                ['id' => 74, 'description' => 'Granola'],
                ['id' => 75, 'description' => 'Filetes de salmon'],
                ['id' => 76, 'description' => 'Cebollín'],
                ['id' => 77, 'description' => 'Salsa agridulce Thai'],
                ['id' => 78, 'description' => 'Cilantro'],
                ['id' => 79, 'description' => 'Sésamo'],
                ['id' => 80, 'description' => 'Polvos de hornear'],
                ['id' => 81, 'description' => 'Esencia de vainilla'],
                ['id' => 82, 'description' => 'Jugo de lima limon'],
                ['id' => 83, 'description' => 'Zeste de lima'],
                ['id' => 84, 'description' => 'Arroz'],
                ['id' => 85, 'description' => 'Caldo de verduras'],
                ['id' => 86, 'description' => 'Levadura nutricional'],
                ['id' => 87, 'description' => 'Zapallito'],
                ['id' => 88, 'description' => 'Zapallito italiano'],
                ['id' => 89, 'description' => 'Ciboulette'],
                ['id' => 90, 'description' => 'Pechuga de pollo'],
                ['id' => 91, 'description' => 'Queso mantecoso'],
                ['id' => 92, 'description' => 'Aceto balsámico'],
                ['id' => 93, 'description' => 'Tomillo'],
                ['id' => 94, 'description' => 'Vodka'],
                ['id' => 95, 'description' => 'Hierba buena'],
                ['id' => 96, 'description' => 'Bebida Ginger Beer'],
                ['id' => 97, 'description' => 'Salsa de tomates'],
                ['id' => 98, 'description' => 'Tortillas de maíz'],
                ['id' => 99, 'description' => 'Porotos negros'],
                ['id' => 100, 'description' => 'Queso feta cremoso'],
                ['id' => 101, 'description' => 'Cilantro castilla'],
                ['id' => 102, 'description' => 'Salsa verde'],
                ['id' => 103, 'description' => 'Crema ácida'],
                ['id' => 104, 'description' => 'Jalapeños'],
                ['id' => 105, 'description' => 'Aceite vegetal'],
                ['id' => 106, 'description' => 'Carne de vacuno'],
                ['id' => 107, 'description' => 'Palta'],
                ['id' => 108, 'description' => 'Brocoli'],
                ['id' => 109, 'description' => 'Salsa de soya'],
                ['id' => 110, 'description' => 'Vino rosé'],
                ['id' => 111, 'description' => 'Agua'],
                ['id' => 112, 'description' => 'Espinaca'],
                ['id' => 113, 'description' => 'Tomate'],
                ['id' => 114, 'description' => 'Carne magra'],
                ['id' => 115, 'description' => 'Choclo'],
                ['id' => 116, 'description' => 'Ralladura de limón'],
                ['id' => 117, 'description' => 'Porotos blancos'],
                ['id' => 118, 'description' => 'Manzanas verdes'],
                ['id' => 119, 'description' => 'Canela'],
                ['id' => 120, 'description' => 'Levadura'],
                ['id' => 121, 'description' => 'Café'],
                ['id' => 122, 'description' => 'Clavo de olor'],
                ['id' => 123, 'description' => 'Nuez moscada molida'],
                ['id' => 124, 'description' => 'Esencia de pan de pascua'],
                ['id' => 125, 'description' => 'Nueces'],
                ['id' => 126, 'description' => 'Fruta confitada'],
                ['id' => 127, 'description' => 'Pasas rubias deshidratadas'],
                ['id' => 128, 'description' => 'Leche condensada'],
                ['id' => 129, 'description' => 'Mayonesa'],
                ['id' => 130, 'description' => 'Alcaparras'],
                ['id' => 131, 'description' => 'Pepinillos dill'],
                ['id' => 132, 'description' => 'Salsa inglesa'],
                ['id' => 133, 'description' => 'Mezcla brownie'],
                ['id' => 134, 'description' => 'Crema batida'],
                ['id' => 135, 'description' => 'Cuscús'],
                ['id' => 136, 'description' => 'Garbanzos'],
                ['id' => 137, 'description' => 'Mezcla de nueces y semillas'],
                ['id' => 138, 'description' => 'Cranberries secos'],
                ['id' => 139, 'description' => 'Berros'],
                ['id' => 140, 'description' => 'Aderezo Khüne'],
                ['id' => 141, 'description' => 'Hojas de rúcula'],
                ['id' => 142, 'description' => 'Estragón'],
                ['id' => 143, 'description' => 'Castañas de cajú'],
                ['id' => 144, 'description' => 'Queso feta o de cabra'],
                ['id' => 145, 'description' => 'Rúcula fresca'],
                ['id' => 146, 'description' => 'Estragón fresco'],
                ['id' => 147, 'description' => 'Castañas de cajú sin sal'],
                ['id' => 148, 'description' => 'Queso feta'],
                ['id' => 149, 'description' => 'Queso de cabra'],
                ['id' => 150, 'description' => 'Pepinos'],
                ['id' => 151, 'description' => 'Pan para sandwich'],
                ['id' => 152, 'description' => 'Churrascos de asiento'],
                ['id' => 153, 'description' => 'Porotos verdes'],
                ['id' => 154, 'description' => 'Ají verde'],
                ['id' => 155, 'description' => 'Gin'],
                ['id' => 156, 'description' => 'Tequila blanco'],
                ['id' => 157, 'description' => 'Triple sec'],
                ['id' => 158, 'description' => 'Goma (Jarabe de goma)'],
                ['id' => 159, 'description' => 'Bebida cola'],
                ['id' => 160, 'description' => 'Limón'],
                ['id' => 161, 'description' => 'Yogurt griego natural'],
                ['id' => 162, 'description' => 'Vinagre blanco'],
                ['id' => 163, 'description' => 'Queso crema'],
                ['id' => 164, 'description' => 'Amaretto'],
                ['id' => 165, 'description' => 'Espumante rosé'],
                ['id' => 166, 'description' => 'Aperol'],
                ['id' => 167, 'description' => 'Agua mineral con gas'],
                ['id' => 168, 'description' => 'Espumante brut'],
                ['id' => 169, 'description' => 'Pomelo'],
                ['id' => 170, 'description' => 'Licor de café'],
                ['id' => 171, 'description' => 'Baileys'],
                ['id' => 172, 'description' => 'Licor de naranja'],
                ['id' => 173, 'description' => 'Tequila'],
                ['id' => 174, 'description' => 'Limonada'],
                ['id' => 175, 'description' => 'Cerveza'],
                ['id' => 176, 'description' => 'Fideos Bauernspätzle'],
                ['id' => 177, 'description' => 'Queso Emmental'],
                ['id' => 178, 'description' => 'Tocino'],
                ['id' => 179, 'description' => 'Ricotta'],
                ['id' => 180, 'description' => 'Salsa Currywurst'],
                ['id' => 181, 'description' => 'Salchichas Vienna'],
                ['id' => 182, 'description' => 'Curry en polvo'],
                ['id' => 183, 'description' => 'Mantequilla de maní'],
                ['id' => 184, 'description' => 'Hojuelas de maíz sin azúcar'],
                ['id' => 185, 'description' => 'Avena hojuelas grandes'],
                ['id' => 186, 'description' => 'Chips de chocolate'],
                ['id' => 187, 'description' => 'Nutella'],
                ['id' => 188, 'description' => 'Tortita de arroz'],
                ['id' => 189, 'description' => 'Tomate cherry'],
                ['id' => 190, 'description' => 'Manzana roja'],
                ['id' => 191, 'description' => 'Naranja'],
                ['id' => 192, 'description' => 'Muesli'],
                ['id' => 193, 'description' => 'Crema'],
                ['id' => 194, 'description' => 'Frambuesas'],
                ['id' => 195, 'description' => 'Mermelada'],
                ['id' => 196, 'description' => 'Kartoffel Puffer (bolitas de papa)'],
                ['id' => 197, 'description' => 'Rotkohl (chucrut morado)'],
                ['id' => 198, 'description' => 'Longanizas Bratwurst'],
                ['id' => 199, 'description' => 'Bratwurst'],
                ['id' => 200, 'description' => 'Mostaza Dijon'],
                ['id' => 201, 'description' => 'Queso cheddar'],
                ['id' => 202, 'description' => 'Pan Integral'],
                ['id' => 203, 'description' => 'Mayonesa Light'],
                ['id' => 204, 'description' => 'Pastrami'],
                ['id' => 205, 'description' => 'Lechuga'],
                ['id' => 206, 'description' => 'Azúcar light'],
                ['id' => 207, 'description' => 'Late harvest'],
                ['id' => 208, 'description' => 'Galletas vainilla molidas'],
                ['id' => 209, 'description' => 'Chorizo'],
                ['id' => 210, 'description' => 'Champiñones'],
                ['id' => 211, 'description' => 'Aceite de canola'],
                ['id' => 212, 'description' => 'Whiskey bourbon'],
                ['id' => 213, 'description' => 'Sal de mar'],
                ['id' => 214, 'description' => 'Ají molido'],
                ['id' => 215, 'description' => 'Salsa barbecue'],
                ['id' => 216, 'description' => 'Mostaza American classic yellow'],
                ['id' => 217, 'description' => 'Chipotles'],
                ['id' => 218, 'description' => 'Té negro'],
                ['id' => 219, 'description' => 'Bebida frutal'],
                ['id' => 220, 'description' => 'Cous cous hidratado'],
                ['id' => 221, 'description' => 'Sandía'],
                ['id' => 222, 'description' => 'Almíbar'],
                ['id' => 223, 'description' => 'Dátiles sin carozo'],
                ['id' => 224, 'description' => 'Cacao amargo'],
                ['id' => 225, 'description' => 'Semillas de chía'],
                ['id' => 226, 'description' => 'Coco rallado'],
                ['id' => 227, 'description' => 'Chocolate negro picado'],
                ['id' => 228, 'description' => 'Avena'],
                ['id' => 229, 'description' => 'Syrup de frambuesa'],
                ['id' => 230, 'description' => 'Carne de pavo molida'],
                ['id' => 231, 'description' => 'Salsa de ostras'],
                ['id' => 232, 'description' => 'Jengibre molido'],
                ['id' => 233, 'description' => 'Cebollín picado fino'],
                ['id' => 234, 'description' => 'Salsa chili'],
                ['id' => 235, 'description' => 'Carne molida de vacuno'],
                ['id' => 236, 'description' => 'Vinagre de arroz'],
                ['id' => 237, 'description' => 'Maicena'],
                ['id' => 238, 'description' => 'Caldo de pescado'],
                ['id' => 239, 'description' => 'Filetes de tilapia'],
                ['id' => 240, 'description' => 'Jugo de tomate'],
                ['id' => 241, 'description' => 'Tabasco'],
                ['id' => 242, 'description' => 'Pimentón asado'],
                ['id' => 243, 'description' => 'Ají escabechado'],
                ['id' => 244, 'description' => 'Cerveza negra de chocolate'],
                ['id' => 245, 'description' => 'Crema de leche light'],
                ['id' => 246, 'description' => 'Brandy'],
                ['id' => 247, 'description' => 'Licor de crema de cacao'],
                ['id' => 248, 'description' => 'Crema líquida'],
                ['id' => 249, 'description' => 'Leche de coco'],
                ['id' => 250, 'description' => 'Crema de coco'],
                ['id' => 251, 'description' => 'Leche evaporada'],
                ['id' => 252, 'description' => 'Campari'],
                ['id' => 253, 'description' => 'Bebida de limón con gas'],
                ['id' => 254, 'description' => 'Melón'],
                ['id' => 255, 'description' => 'Gin tonic'],
                ['id' => 256, 'description' => 'Pimienta de cayena'],
                ['id' => 257, 'description' => 'Rama de vainilla'],
                ['id' => 258, 'description' => 'Chardonnay'],
                ['id' => 259, 'description' => 'Whisky'],
                ['id' => 260, 'description' => 'Marshmallows'],
                ['id' => 261, 'description' => 'Tahini'],
                ['id' => 262, 'description' => 'Supremas de pollo'],
                ['id' => 263, 'description' => 'Mozzarella de búfala'],
                ['id' => 264, 'description' => 'Tomate limachino'],
                ['id' => 265, 'description' => 'Pan Ciabatta'],
                ['id' => 266, 'description' => 'Quinoa'],
                ['id' => 267, 'description' => 'Pescado'],
                ['id' => 268, 'description' => 'Semillas de maravilla'],
                ['id' => 269, 'description' => 'Merluza'],
                ['id' => 270, 'description' => 'Congrio'],
                ['id' => 271, 'description' => 'Reineta'],
                ['id' => 272, 'description' => 'Marraquetas'],
                ['id' => 273, 'description' => 'Rúcula baby'],
                ['id' => 274, 'description' => 'Repollo'],
                ['id' => 275, 'description' => 'Helado de vainilla'],
                ['id' => 276, 'description' => 'Salsa de frambuesa'],
                ['id' => 277, 'description' => 'Almendras'],
                ['id' => 278, 'description' => 'Durazno'],
                ['id' => 279, 'description' => 'Mascarpone'],
                ['id' => 280, 'description' => 'Galletas de champaña'],
                ['id' => 281, 'description' => 'Café cargado'],
                ['id' => 282, 'description' => 'Cacao amargo en polvo'],
                ['id' => 283, 'description' => 'Acelga'],
                ['id' => 284, 'description' => 'Aceite spray'],
                ['id' => 285, 'description' => 'Endulzante en polvo'],
                ['id' => 286, 'description' => 'Mermelada sin azúcar'],
                ['id' => 287, 'description' => 'Manjar sin azúcar'],
                ['id' => 288, 'description' => 'Chocolate sin azúcar'],
                ['id' => 289, 'description' => 'Puré de zapallo camote'],
                ['id' => 290, 'description' => 'Tagatosa'],
                ['id' => 291, 'description' => 'Cacao sin azúcar'],
                ['id' => 292, 'description' => 'Leche líquida descremada'],
                ['id' => 293, 'description' => 'Harina de avena'],
                ['id' => 294, 'description' => 'Harina integral'],
                ['id' => 295, 'description' => 'Trozos de chocolate sin azúcar'],
                ['id' => 296, 'description' => 'Helado de vainilla sin azúcar'],
                ['id' => 297, 'description' => 'Salsa de chocolate sin azúcar'],
                ['id' => 298, 'description' => 'Galletas sin azúcar Digestive de chocolate'],
                ['id' => 299, 'description' => 'Quesillo 0% grasa'],
                ['id' => 300, 'description' => 'Manjar con azúcar'],
                ['id' => 301, 'description' => 'Crema chantilly light sin azúcar'],
                ['id' => 302, 'description' => 'Cebollines'],
                ['id' => 303, 'description' => 'Cacao en polvo sin azúcar'],
                ['id' => 304, 'description' => 'Tagatosa o endulzante granulado'],
                ['id' => 305, 'description' => 'Galletas de vino'],
                ['id' => 306, 'description' => 'Crema para batir o crema chantilly'],
                ['id' => 307, 'description' => 'Syrup de chocolate'],
                ['id' => 308, 'description' => 'Harina sin polvos'],
                ['id' => 309, 'description' => 'Manteca'],
                ['id' => 310, 'description' => 'Endulzante'],
                ['id' => 311, 'description' => 'Leche de coco sin azúcar'],
                ['id' => 312, 'description' => 'Cacao amargo 100% Pacari'],
                ['id' => 313, 'description' => 'Harina de coco'],
                ['id' => 314, 'description' => 'Chocolate Pacari 72% cacao trozado'],
                ['id' => 315, 'description' => 'Semillas de sésamo'],
                ['id' => 316, 'description' => 'Vino pipeño'],
                ['id' => 317, 'description' => 'Helado de piña'],
                ['id' => 318, 'description' => 'Granadina'],
            ]);
        }
    }
}
